name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]      # runs automatically for every push to main
  workflow_dispatch:      # lets you press “Run workflow” in the UI

permissions:
  contents: read          # clone repo
  pages: write            # upload pages artifact
  id-token: write         # publish the deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install, build, and upload in one step
      - uses: withastro/action@v3
        # Uncomment the next line if you use pnpm, bun, etc.
        # with:
        #   package-manager: pnpm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
